name: HeroBounty
version: 1.7.7
author: DThielke
main: com.herocraftonline.dthielke.herobounty.HeroBounty
description: Provides a bounty system with iConomy support
commands:
  bounty:
    description:  Lists all HeroBounty commands 
    usage: /<command> help